var matchTypes = ['League', 'Knock-Out', 'Quarter-Final', 'Semi-Final', 'Final'];

var teamList = [
{ "TId": 1, "FName": "Argentina- Aldosivi", "TName": "Aldosivi" },
{ "TId": 2, "FName": "Argentina- Arsenal de Sarandi", "TName": "Arsenal de Sarandi" },
{ "TId": 3, "FName": "Argentina- Atletico de Rafaela", "TName": "Atletico de Rafaela" },
{ "TId": 4, "FName": "Argentina- Atletico Tucuman", "TName": "Atletico Tucuman" },
{ "TId": 5, "FName": "Argentina- Banfield", "TName": "Banfield" },
{ "TId": 6, "FName": "Argentina- Belgrano de Cordoba", "TName": "Belgrano de Cordoba" },
{ "TId": 7, "FName": "Argentina- Boca Juniors", "TName": "Boca Juniors" },
{ "TId": 8, "FName": "Argentina- Club Atletico Tigre", "TName": "Club Atletico Tigre" },
{ "TId": 9, "FName": "Argentina- Colon", "TName": "Colon" },
{ "TId": 10, "FName": "Argentina- Defensa y Justicia", "TName": "Defensa y Justicia" },
{ "TId": 11, "FName": "Argentina- Estudiantes de La Plata", "TName": "Estudiantes de La Plata" },
{ "TId": 12, "FName": "Argentina- Gimnasia y Esgrima La Plata", "TName": "Gimnasia y Esgrima La Plata" },
{ "TId": 13, "FName": "Argentina- Godoy Cruz", "TName": "Godoy Cruz" },
{ "TId": 14, "FName": "Argentina- Huracan", "TName": "Huracan" },
{ "TId": 15, "FName": "Argentina- Independiente", "TName": "Independiente" },
{ "TId": 16, "FName": "Argentina- Lanus", "TName": "Lanus" },
{ "TId": 17, "FName": "Argentina- Newell's Old Boys", "TName": "Newell's Old Boys" },
{ "TId": 18, "FName": "Argentina- Olimpo Bahía Blanca", "TName": "Olimpo Bahía Blanca" },
{ "TId": 19, "FName": "Argentina- Patronato", "TName": "Patronato" },
{ "TId": 20, "FName": "Argentina- Quilmes Atletico Club", "TName": "Quilmes Atletico Club" },
{ "TId": 21, "FName": "Argentina- Racing Club de Avellaneda", "TName": "Racing Club de Avellaneda" },
{ "TId": 22, "FName": "Argentina- River Plate", "TName": "River Plate" },
{ "TId": 23, "FName": "Argentina- Rosario Central", "TName": "Rosario Central" },
{ "TId": 24, "FName": "Argentina- San Lorenzo de Almagro", "TName": "San Lorenzo de Almagro" },
{ "TId": 25, "FName": "Argentina- San Martín de San Juan", "TName": "San Martín de San Juan" },
{ "TId": 26, "FName": "Argentina- Sarmiento", "TName": "Sarmiento" },
{ "TId": 27, "FName": "Argentina- Talleres de Cordoba", "TName": "Talleres de Cordoba" },
{ "TId": 28, "FName": "Argentina- Temperley", "TName": "Temperley" },
{ "TId": 29, "FName": "Argentina- Union Santa Fe", "TName": "Union Santa Fe" },
{ "TId": 30, "FName": "Argentina- Velez Sarsfield", "TName": "Velez Sarsfield" },
{ "TId": 31, "FName": "Australia- Adelaide United", "TName": "Adelaide United" },
{ "TId": 32, "FName": "Australia- Brisbane Roar", "TName": "Brisbane Roar" },
{ "TId": 33, "FName": "Australia- Central Coast Mariners", "TName": "Central Coast Mariners" },
{ "TId": 34, "FName": "Australia- Melbourne City", "TName": "Melbourne City" },
{ "TId": 35, "FName": "Australia- Melbourne Victory", "TName": "Melbourne Victory" },
{ "TId": 36, "FName": "Australia- Newcastle Jets", "TName": "Newcastle Jets" },
{ "TId": 37, "FName": "Australia- Perth Glory", "TName": "Perth Glory" },
{ "TId": 38, "FName": "Australia- Sydney FC", "TName": "Sydney FC" },
{ "TId": 39, "FName": "Australia- Wellington Phoenix", "TName": "Wellington Phoenix" },
{ "TId": 40, "FName": "Australia- Western Sydney Wanderers", "TName": "Western Sydney Wanderers" },
{ "TId": 41, "FName": "Austria- Austria Wien", "TName": "Austria Wien" },
{ "TId": 42, "FName": "Austria- FC Admira Wacker Modling", "TName": "FC Admira Wacker Modling" },
{ "TId": 43, "FName": "Austria- Rapid Wien", "TName": "Rapid Wien" },
{ "TId": 44, "FName": "Austria- Red Bull Salzburg", "TName": "Red Bull Salzburg" },
{ "TId": 45, "FName": "Austria- SCR Altach", "TName": "SCR Altach" },
{ "TId": 46, "FName": "Austria- SKN St. Polten", "TName": "SKN St. Polten" },
{ "TId": 47, "FName": "Austria- Sturm Graz", "TName": "Sturm Graz" },
{ "TId": 48, "FName": "Austria- SV Mattersburg", "TName": "SV Mattersburg" },
{ "TId": 49, "FName": "Austria- SV Ried", "TName": "SV Ried" },
{ "TId": 50, "FName": "Austria- Wolfsberger AC", "TName": "Wolfsberger AC" },
{ "TId": 51, "FName": "Belgium- Club Brugge", "TName": "Club Brugge" },
{ "TId": 52, "FName": "Belgium- Excel Mouscron", "TName": "Excel Mouscron" },
{ "TId": 53, "FName": "Belgium- KAA Gent", "TName": "KAA Gent" },
{ "TId": 54, "FName": "Belgium- KAS Eupen", "TName": "KAS Eupen" },
{ "TId": 55, "FName": "Belgium- KRC Genk", "TName": "KRC Genk" },
{ "TId": 56, "FName": "Belgium- KV Kortrijk", "TName": "KV Kortrijk" },
{ "TId": 57, "FName": "Belgium- KV Mechelen", "TName": "KV Mechelen" },
{ "TId": 58, "FName": "Belgium- KV Oostende", "TName": "KV Oostende" },
{ "TId": 59, "FName": "Belgium- KVC Westerlo", "TName": "KVC Westerlo" },
{ "TId": 60, "FName": "Belgium- RSC Anderlecht", "TName": "RSC Anderlecht" },
{ "TId": 61, "FName": "Belgium- Sint-Truiden", "TName": "Sint-Truiden" },
{ "TId": 62, "FName": "Belgium- Sp. Charleroi", "TName": "Sp. Charleroi" },
{ "TId": 63, "FName": "Belgium- Sport. Lokeren", "TName": "Sport. Lokeren" },
{ "TId": 64, "FName": "Belgium- Standard Liège", "TName": "Standard Liège" },
{ "TId": 65, "FName": "Belgium- Waasland-Beveren", "TName": "Waasland-Beveren" },
{ "TId": 66, "FName": "Belgium- Zulte-Waregem", "TName": "Zulte-Waregem" },
{ "TId": 67, "FName": "Brazil- America Mineiro", "TName": "America Mineiro" },
{ "TId": 68, "FName": "Brazil- Atletico Mineiro", "TName": "Atletico Mineiro" },
{ "TId": 69, "FName": "Brazil- Atletico Paranaense", "TName": "Atletico Paranaense" },
{ "TId": 70, "FName": "Brazil- Botafogo", "TName": "Botafogo" },
{ "TId": 71, "FName": "Brazil- Chapecoense", "TName": "Chapecoense" },
{ "TId": 72, "FName": "Brazil- Coritiba", "TName": "Coritiba" },
{ "TId": 73, "FName": "Brazil- Cruzeiro", "TName": "Cruzeiro" },
{ "TId": 74, "FName": "Brazil- Figueirense", "TName": "Figueirense" },
{ "TId": 75, "FName": "Brazil- Fluminense", "TName": "Fluminense" },
{ "TId": 76, "FName": "Brazil- Gremio", "TName": "Gremio" },
{ "TId": 77, "FName": "Brazil- Internacional", "TName": "Internacional" },
{ "TId": 78, "FName": "Brazil- Palmeiras", "TName": "Palmeiras" },
{ "TId": 79, "FName": "Brazil- Ponte Preta", "TName": "Ponte Preta" },
{ "TId": 80, "FName": "Brazil- Santa Cruz", "TName": "Santa Cruz" },
{ "TId": 81, "FName": "Brazil- Santos", "TName": "Santos" },
{ "TId": 82, "FName": "Brazil- Sao Paulo", "TName": "Sao Paulo" },
{ "TId": 83, "FName": "Brazil- Sport", "TName": "Sport" },
{ "TId": 84, "FName": "Brazil- Vitoria", "TName": "Vitoria" },
{ "TId": 85, "FName": "Chile- Audax Italiano", "TName": "Audax Italiano" },
{ "TId": 86, "FName": "Chile- CD Huachipato", "TName": "CD Huachipato" },
{ "TId": 87, "FName": "Chile- CD O'Higgins", "TName": "CD O'Higgins" },
{ "TId": 88, "FName": "Chile- CD Palestino", "TName": "CD Palestino" },
{ "TId": 89, "FName": "Chile- Cobresal", "TName": "Cobresal" },
{ "TId": 90, "FName": "Chile- Colo-Colo", "TName": "Colo-Colo" },
{ "TId": 91, "FName": "Chile- Deportes Antofagasta", "TName": "Deportes Antofagasta" },
{ "TId": 92, "FName": "Chile- Deportes Iquique", "TName": "Deportes Iquique" },
{ "TId": 93, "FName": "Chile- Deportes Temuco", "TName": "Deportes Temuco" },
{ "TId": 94, "FName": "Chile- Everton de Vina del Mar", "TName": "Everton de Vina del Mar" },
{ "TId": 95, "FName": "Chile- San Luis de Quillota", "TName": "San Luis de Quillota" },
{ "TId": 96, "FName": "Chile- Santiago Wanderers", "TName": "Santiago Wanderers" },
{ "TId": 97, "FName": "Chile- Union Espanola", "TName": "Union Espanola" },
{ "TId": 98, "FName": "Chile- Universidad Catolica", "TName": "Universidad Catolica" },
{ "TId": 99, "FName": "Chile- Universidad de Chile", "TName": "Universidad de Chile" },
{ "TId": 100, "FName": "Chile- Universidad de Concepcion", "TName": "Universidad de Concepcion" },
{ "TId": 101, "FName": "Colombia- Alianza Petrolera", "TName": "Alianza Petrolera" },
{ "TId": 102, "FName": "Colombia- Atletico Bucaramanga", "TName": "Atletico Bucaramanga" },
{ "TId": 103, "FName": "Colombia- Atletico Huila", "TName": "Atletico Huila" },
{ "TId": 104, "FName": "Colombia- Atletico Nacional", "TName": "Atletico Nacional" },
{ "TId": 105, "FName": "Colombia- Boyaca Chico", "TName": "Boyaca Chico" },
{ "TId": 106, "FName": "Colombia- Cortulua", "TName": "Cortulua" },
{ "TId": 107, "FName": "Colombia- Deportes Tolima", "TName": "Deportes Tolima" },
{ "TId": 108, "FName": "Colombia- Deportivo Cali", "TName": "Deportivo Cali" },
{ "TId": 109, "FName": "Colombia- Deportivo Pasto", "TName": "Deportivo Pasto" },
{ "TId": 110, "FName": "Colombia- Envigado", "TName": "Envigado" },
{ "TId": 111, "FName": "Colombia- Fortaleza CEIF", "TName": "Fortaleza CEIF" },
{ "TId": 112, "FName": "Colombia- Independiente Medellín", "TName": "Independiente Medellín" },
{ "TId": 113, "FName": "Colombia- Independiente Santa Fe", "TName": "Independiente Santa Fe" },
{ "TId": 114, "FName": "Colombia- Jaguares de Cordoba", "TName": "Jaguares de Cordoba" },
{ "TId": 115, "FName": "Colombia- Junior Barranquilla", "TName": "Junior Barranquilla" },
{ "TId": 116, "FName": "Colombia- La Equidad", "TName": "La Equidad" },
{ "TId": 117, "FName": "Colombia- Millonarios", "TName": "Millonarios" },
{ "TId": 118, "FName": "Colombia- Once Caldas", "TName": "Once Caldas" },
{ "TId": 119, "FName": "Colombia- Patriotas Boyaca", "TName": "Patriotas Boyaca" },
{ "TId": 120, "FName": "Colombia- Rionegro aguilas", "TName": "Rionegro aguilas" },
{ "TId": 121, "FName": "Denmark- Aalborg BK", "TName": "Aalborg BK" },
{ "TId": 122, "FName": "Denmark- Aarhus GF", "TName": "Aarhus GF" },
{ "TId": 123, "FName": "Denmark- AC Horsens", "TName": "AC Horsens" },
{ "TId": 124, "FName": "Denmark- Brondby IF", "TName": "Brondby IF" },
{ "TId": 125, "FName": "Denmark- Esbjerg fB", "TName": "Esbjerg fB" },
{ "TId": 126, "FName": "Denmark- FC Kobenhavn", "TName": "FC Kobenhavn" },
{ "TId": 127, "FName": "Denmark- FC Midtjylland", "TName": "FC Midtjylland" },
{ "TId": 128, "FName": "Denmark- FC Nordsjælland", "TName": "FC Nordsjælland" },
{ "TId": 129, "FName": "Denmark- Lyngby BK", "TName": "Lyngby BK" },
{ "TId": 130, "FName": "Denmark- Odense Boldklub", "TName": "Odense Boldklub" },
{ "TId": 131, "FName": "Denmark- Randers FC", "TName": "Randers FC" },
{ "TId": 132, "FName": "Denmark- Silkeborg IF", "TName": "Silkeborg IF" },
{ "TId": 133, "FName": "Denmark- SonderjyskE", "TName": "SonderjyskE" },
{ "TId": 134, "FName": "Denmark- Viborg FF", "TName": "Viborg FF" },
{ "TId": 135, "FName": "England- Accrington Stanley", "TName": "Accrington Stanley" },
{ "TId": 136, "FName": "England- AFC Wimbledon", "TName": "AFC Wimbledon" },
{ "TId": 137, "FName": "England- Arsenal", "TName": "Arsenal" },
{ "TId": 138, "FName": "England- Aston Villa", "TName": "Aston Villa" },
{ "TId": 139, "FName": "England- Barnet", "TName": "Barnet" },
{ "TId": 140, "FName": "England- Barnsley", "TName": "Barnsley" },
{ "TId": 141, "FName": "England- Birmingham City", "TName": "Birmingham City" },
{ "TId": 142, "FName": "England- Blackburn Rovers", "TName": "Blackburn Rovers" },
{ "TId": 143, "FName": "England- Blackpool", "TName": "Blackpool" },
{ "TId": 144, "FName": "England- Bolton Wanderers", "TName": "Bolton Wanderers" },
{ "TId": 145, "FName": "England- Bournemouth", "TName": "Bournemouth" },
{ "TId": 146, "FName": "England- Bradford City", "TName": "Bradford City" },
{ "TId": 147, "FName": "England- Brentford", "TName": "Brentford" },
{ "TId": 148, "FName": "England- Brighton & Hove Albion", "TName": "Brighton & Hove Albion" },
{ "TId": 149, "FName": "England- Bristol City", "TName": "Bristol City" },
{ "TId": 150, "FName": "England- Bristol Rovers", "TName": "Bristol Rovers" },
{ "TId": 151, "FName": "England- Burnley", "TName": "Burnley" },
{ "TId": 152, "FName": "England- Burton Albion", "TName": "Burton Albion" },
{ "TId": 153, "FName": "England- Bury", "TName": "Bury" },
{ "TId": 154, "FName": "England- Cambridge United", "TName": "Cambridge United" },
{ "TId": 155, "FName": "England- Cardiff City", "TName": "Cardiff City" },
{ "TId": 156, "FName": "England- Carlisle United", "TName": "Carlisle United" },
{ "TId": 157, "FName": "England- Charlton Athletic", "TName": "Charlton Athletic" },
{ "TId": 158, "FName": "England- Chelsea", "TName": "Chelsea" },
{ "TId": 159, "FName": "England- Cheltenham Town", "TName": "Cheltenham Town" },
{ "TId": 160, "FName": "England- Chesterfield", "TName": "Chesterfield" },
{ "TId": 161, "FName": "England- Colchester United", "TName": "Colchester United" },
{ "TId": 162, "FName": "England- Coventry City", "TName": "Coventry City" },
{ "TId": 163, "FName": "England- Crawley Town", "TName": "Crawley Town" },
{ "TId": 164, "FName": "England- Crewe Alexandra", "TName": "Crewe Alexandra" },
{ "TId": 165, "FName": "England- Crystal Palace", "TName": "Crystal Palace" },
{ "TId": 166, "FName": "England- Derby County", "TName": "Derby County" },
{ "TId": 167, "FName": "England- Doncaster Rovers", "TName": "Doncaster Rovers" },
{ "TId": 168, "FName": "England- Everton", "TName": "Everton" },
{ "TId": 169, "FName": "England- Exeter City", "TName": "Exeter City" },
{ "TId": 170, "FName": "England- Fleetwood Town", "TName": "Fleetwood Town" },
{ "TId": 171, "FName": "England- Fulham", "TName": "Fulham" },
{ "TId": 172, "FName": "England- Gillingham", "TName": "Gillingham" },
{ "TId": 173, "FName": "England- Grimsby Town", "TName": "Grimsby Town" },
{ "TId": 174, "FName": "England- Hartlepool United", "TName": "Hartlepool United" },
{ "TId": 175, "FName": "England- Huddersfield Town", "TName": "Huddersfield Town" },
{ "TId": 176, "FName": "England- Hull City", "TName": "Hull City" },
{ "TId": 177, "FName": "England- Ipswich Town", "TName": "Ipswich Town" },
{ "TId": 178, "FName": "England- Leeds United", "TName": "Leeds United" },
{ "TId": 179, "FName": "England- Leicester City", "TName": "Leicester City" },
{ "TId": 180, "FName": "England- Leyton Orient", "TName": "Leyton Orient" },
{ "TId": 181, "FName": "England- Liverpool", "TName": "Liverpool" },
{ "TId": 182, "FName": "England- Luton Town", "TName": "Luton Town" },
{ "TId": 183, "FName": "England- Manchester City", "TName": "Manchester City" },
{ "TId": 184, "FName": "England- Manchester United", "TName": "Manchester United" },
{ "TId": 185, "FName": "England- Mansfield Town", "TName": "Mansfield Town" },
{ "TId": 186, "FName": "England- Middlesbrough", "TName": "Middlesbrough" },
{ "TId": 187, "FName": "England- Millwall", "TName": "Millwall" },
{ "TId": 188, "FName": "England- Milton Keynes Dons", "TName": "Milton Keynes Dons" },
{ "TId": 189, "FName": "England- Morecambe", "TName": "Morecambe" },
{ "TId": 190, "FName": "England- Newcastle United", "TName": "Newcastle United" },
{ "TId": 191, "FName": "England- Newport County", "TName": "Newport County" },
{ "TId": 192, "FName": "England- Northampton Town", "TName": "Northampton Town" },
{ "TId": 193, "FName": "England- Norwich City", "TName": "Norwich City" },
{ "TId": 194, "FName": "England- Nottingham Forest", "TName": "Nottingham Forest" },
{ "TId": 195, "FName": "England- Notts County", "TName": "Notts County" },
{ "TId": 196, "FName": "England- Oldham Athletic", "TName": "Oldham Athletic" },
{ "TId": 197, "FName": "England- Oxford United", "TName": "Oxford United" },
{ "TId": 198, "FName": "England- Peterborough United", "TName": "Peterborough United" },
{ "TId": 199, "FName": "England- Plymouth Argyle", "TName": "Plymouth Argyle" },
{ "TId": 200, "FName": "England- Port Vale", "TName": "Port Vale" },
{ "TId": 201, "FName": "England- Portsmouth", "TName": "Portsmouth" },
{ "TId": 202, "FName": "England- Preston North End", "TName": "Preston North End" },
{ "TId": 203, "FName": "England- Queens Park Rangers", "TName": "Queens Park Rangers" },
{ "TId": 204, "FName": "England- Reading", "TName": "Reading" },
{ "TId": 205, "FName": "England- Rochdale", "TName": "Rochdale" },
{ "TId": 206, "FName": "England- Rotherham United", "TName": "Rotherham United" },
{ "TId": 207, "FName": "England- Scunthorpe United", "TName": "Scunthorpe United" },
{ "TId": 208, "FName": "England- Sheffield United", "TName": "Sheffield United" },
{ "TId": 209, "FName": "England- Sheffield Wednesday", "TName": "Sheffield Wednesday" },
{ "TId": 210, "FName": "England- Shrewsbury Town", "TName": "Shrewsbury Town" },
{ "TId": 211, "FName": "England- Southampton", "TName": "Southampton" },
{ "TId": 212, "FName": "England- Southend United", "TName": "Southend United" },
{ "TId": 213, "FName": "England- Stevenage", "TName": "Stevenage" },
{ "TId": 214, "FName": "England- Stoke City", "TName": "Stoke City" },
{ "TId": 215, "FName": "England- Sunderland", "TName": "Sunderland" },
{ "TId": 216, "FName": "England- Swansea City", "TName": "Swansea City" },
{ "TId": 217, "FName": "England- Swindon Town", "TName": "Swindon Town" },
{ "TId": 218, "FName": "England- Tottenham Hotspur", "TName": "Tottenham Hotspur" },
{ "TId": 219, "FName": "England- Walsall", "TName": "Walsall" },
{ "TId": 220, "FName": "England- Watford", "TName": "Watford" },
{ "TId": 221, "FName": "England- West Bromwich Albion", "TName": "West Bromwich Albion" },
{ "TId": 222, "FName": "England- West Ham United", "TName": "West Ham United" },
{ "TId": 223, "FName": "England- Wigan Athletic", "TName": "Wigan Athletic" },
{ "TId": 224, "FName": "England- Wolverhampton Wanderers", "TName": "Wolverhampton Wanderers" },
{ "TId": 225, "FName": "England- Wycombe Wanderers", "TName": "Wycombe Wanderers" },
{ "TId": 226, "FName": "England- Yeovil Town", "TName": "Yeovil Town" },
{ "TId": 227, "FName": "France- AC Ajaccio", "TName": "AC Ajaccio" },
{ "TId": 228, "FName": "France- AJ Auxerre", "TName": "AJ Auxerre" },
{ "TId": 229, "FName": "France- Amiens SC", "TName": "Amiens SC" },
{ "TId": 230, "FName": "France- Angers SCO", "TName": "Angers SCO" },
{ "TId": 231, "FName": "France- AS Monaco", "TName": "AS Monaco" },
{ "TId": 232, "FName": "France- AS Nancy", "TName": "AS Nancy" },
{ "TId": 233, "FName": "France- AS Saint-etienne", "TName": "AS Saint-etienne" },
{ "TId": 234, "FName": "France- Bourg en Bresse 01", "TName": "Bourg en Bresse 01" },
{ "TId": 235, "FName": "France- Chamois Niortais FC", "TName": "Chamois Niortais FC" },
{ "TId": 236, "FName": "France- Clermont Foot", "TName": "Clermont Foot" },
{ "TId": 237, "FName": "France- Dijon Football", "TName": "Dijon Football" },
{ "TId": 238, "FName": "France- En Avant Guingamp", "TName": "En Avant Guingamp" },
{ "TId": 239, "FName": "France- ES Troyes AC", "TName": "ES Troyes AC" },
{ "TId": 240, "FName": "France- FC Lorient", "TName": "FC Lorient" },
{ "TId": 241, "FName": "France- FC Metz", "TName": "FC Metz" },
{ "TId": 242, "FName": "France- FC Nantes", "TName": "FC Nantes" },
{ "TId": 243, "FName": "France- FC Sochaux", "TName": "FC Sochaux" },
{ "TId": 244, "FName": "France- GFC Ajaccio", "TName": "GFC Ajaccio" },
{ "TId": 245, "FName": "France- Girondins de Bordeaux", "TName": "Girondins de Bordeaux" },
{ "TId": 246, "FName": "France- Le Havre AC", "TName": "Le Havre AC" },
{ "TId": 247, "FName": "France- LOSC Lille", "TName": "LOSC Lille" },
{ "TId": 248, "FName": "France- Montpellier HSC", "TName": "Montpellier HSC" },
{ "TId": 249, "FName": "France- Nîmes Olympique", "TName": "Nîmes Olympique" },
{ "TId": 250, "FName": "France- OGC Nice", "TName": "OGC Nice" },
{ "TId": 251, "FName": "France- Olympique de Marseille", "TName": "Olympique de Marseille" },
{ "TId": 252, "FName": "France- Olympique Lyonnais", "TName": "Olympique Lyonnais" },
{ "TId": 253, "FName": "France- Paris Saint-Germain", "TName": "Paris Saint-Germain" },
{ "TId": 254, "FName": "France- Racing Club de Lens", "TName": "Racing Club de Lens" },
{ "TId": 255, "FName": "France- RC Strasbourg", "TName": "RC Strasbourg" },
{ "TId": 256, "FName": "France- Red Star FC", "TName": "Red Star FC" },
{ "TId": 257, "FName": "France- SC Bastia", "TName": "SC Bastia" },
{ "TId": 258, "FName": "France- SM Caen", "TName": "SM Caen" },
{ "TId": 259, "FName": "France- Stade Brestois 29", "TName": "Stade Brestois 29" },
{ "TId": 260, "FName": "France- Stade de Reims", "TName": "Stade de Reims" },
{ "TId": 261, "FName": "France- Stade Lavallois MFC", "TName": "Stade Lavallois MFC" },
{ "TId": 262, "FName": "France- Stade Rennais", "TName": "Stade Rennais" },
{ "TId": 263, "FName": "France- Toulouse FC", "TName": "Toulouse FC" },
{ "TId": 264, "FName": "France- Tours FC", "TName": "Tours FC" },
{ "TId": 265, "FName": "France- US Orleans", "TName": "US Orleans" },
{ "TId": 266, "FName": "France- Valenciennes FC", "TName": "Valenciennes FC" },
{ "TId": 267, "FName": "Germany- 1. FC Heidenheim", "TName": "1. FC Heidenheim" },
{ "TId": 268, "FName": "Germany- 1. FC Kaiserslautern", "TName": "1. FC Kaiserslautern" },
{ "TId": 269, "FName": "Germany- 1. FC Koln", "TName": "1. FC Koln" },
{ "TId": 270, "FName": "Germany- 1. FC Nnurnberg", "TName": "1. FC Nnurnberg" },
{ "TId": 271, "FName": "Germany- 1. FC Union Berlin", "TName": "1. FC Union Berlin" },
{ "TId": 272, "FName": "Germany- 1. FSV Mainz 05", "TName": "1. FSV Mainz 05" },
{ "TId": 273, "FName": "Germany- Arminia Bielefeld", "TName": "Arminia Bielefeld" },
{ "TId": 274, "FName": "Germany- Bayer 04 Leverkusen", "TName": "Bayer 04 Leverkusen" },
{ "TId": 275, "FName": "Germany- Bayern Mnunchen", "TName": "Bayern Mnunchen" },
{ "TId": 276, "FName": "Germany- Borussia Dortmund", "TName": "Borussia Dortmund" },
{ "TId": 277, "FName": "Germany- Borussia M'gladbach", "TName": "Borussia M'gladbach" },
{ "TId": 278, "FName": "Germany- Dynamo Dresden", "TName": "Dynamo Dresden" },
{ "TId": 279, "FName": "Germany- Eintracht Braunschweig", "TName": "Eintracht Braunschweig" },
{ "TId": 280, "FName": "Germany- Eintracht Frankfurt", "TName": "Eintracht Frankfurt" },
{ "TId": 281, "FName": "Germany- Erzgebirge Aue", "TName": "Erzgebirge Aue" },
{ "TId": 282, "FName": "Germany- FC Augsburg", "TName": "FC Augsburg" },
{ "TId": 283, "FName": "Germany- FC Ingolstadt 04", "TName": "FC Ingolstadt 04" },
{ "TId": 284, "FName": "Germany- FC Schalke 04", "TName": "FC Schalke 04" },
{ "TId": 285, "FName": "Germany- FC St. Pauli", "TName": "FC St. Pauli" },
{ "TId": 286, "FName": "Germany- Fortuna Dnusseldorf", "TName": "Fortuna Dnusseldorf" },
{ "TId": 287, "FName": "Germany- Hamburger SV", "TName": "Hamburger SV" },
{ "TId": 288, "FName": "Germany- Hannover 96", "TName": "Hannover 96" },
{ "TId": 289, "FName": "Germany- Hertha BSC", "TName": "Hertha BSC" },
{ "TId": 290, "FName": "Germany- Karlsruher SC", "TName": "Karlsruher SC" },
{ "TId": 291, "FName": "Germany- RB Leipzig", "TName": "RB Leipzig" },
{ "TId": 292, "FName": "Germany- SC Freiburg", "TName": "SC Freiburg" },
{ "TId": 293, "FName": "Germany- SpVgg Greuther Fnurth", "TName": "SpVgg Greuther Fnurth" },
{ "TId": 294, "FName": "Germany- SV Darmstadt 98", "TName": "SV Darmstadt 98" },
{ "TId": 295, "FName": "Germany- SV Sandhausen", "TName": "SV Sandhausen" },
{ "TId": 296, "FName": "Germany- SV Werder Bremen", "TName": "SV Werder Bremen" },
{ "TId": 297, "FName": "Germany- TSG 1899 Hoffenheim", "TName": "TSG 1899 Hoffenheim" },
{ "TId": 298, "FName": "Germany- TSV 1860 Mnunchen", "TName": "TSV 1860 Mnunchen" },
{ "TId": 299, "FName": "Germany- VfB Stuttgart", "TName": "VfB Stuttgart" },
{ "TId": 300, "FName": "Germany- VfL Bochum", "TName": "VfL Bochum" },
{ "TId": 301, "FName": "Germany- VfL Wolfsburg", "TName": "VfL Wolfsburg" },
{ "TId": 302, "FName": "Germany- Wnurzburger Kickers", "TName": "Wnurzburger Kickers" },
{ "TId": 303, "FName": "International- Argentina", "TName": "Argentina" },
{ "TId": 304, "FName": "International- Australia", "TName": "Australia" },
{ "TId": 305, "FName": "International- Australia - Women", "TName": "Australia - Women" },
{ "TId": 306, "FName": "International- Austria", "TName": "Austria" },
{ "TId": 307, "FName": "International- Belgium", "TName": "Belgium" },
{ "TId": 308, "FName": "International- Bolivia", "TName": "Bolivia" },
{ "TId": 309, "FName": "International- Brazil", "TName": "Brazil" },
{ "TId": 310, "FName": "International- Brazil - Women", "TName": "Brazil - Women" },
{ "TId": 311, "FName": "International- Bulgaria", "TName": "Bulgaria" },
{ "TId": 312, "FName": "International- Cameroon", "TName": "Cameroon" },
{ "TId": 313, "FName": "International- Canada", "TName": "Canada" },
{ "TId": 314, "FName": "International- Canada - Women", "TName": "Canada - Women" },
{ "TId": 315, "FName": "International- Chile", "TName": "Chile" },
{ "TId": 316, "FName": "International- China PR", "TName": "China PR" },
{ "TId": 317, "FName": "International- China PR - Women", "TName": "China PR - Women" },
{ "TId": 318, "FName": "International- Colombia", "TName": "Colombia" },
{ "TId": 319, "FName": "International- Cote d'Ivoire", "TName": "Cote d'Ivoire" },
{ "TId": 320, "FName": "International- Czech Republic", "TName": "Czech Republic" },
{ "TId": 321, "FName": "International- Denmark", "TName": "Denmark" },
{ "TId": 322, "FName": "International- Ecuador", "TName": "Ecuador" },
{ "TId": 323, "FName": "International- Egypt", "TName": "Egypt" },
{ "TId": 324, "FName": "International- England", "TName": "England" },
{ "TId": 325, "FName": "International- England - Women", "TName": "England - Women" },
{ "TId": 326, "FName": "International- Finland", "TName": "Finland" },
{ "TId": 327, "FName": "International- France", "TName": "France" },
{ "TId": 328, "FName": "International- France - Women", "TName": "France - Women" },
{ "TId": 329, "FName": "International- Germany", "TName": "Germany" },
{ "TId": 330, "FName": "International- Germany - Women", "TName": "Germany - Women" },
{ "TId": 331, "FName": "International- Greece", "TName": "Greece" },
{ "TId": 332, "FName": "International- Hungary", "TName": "Hungary" },
{ "TId": 333, "FName": "International- India", "TName": "India" },
{ "TId": 334, "FName": "International- Italy", "TName": "Italy" },
{ "TId": 335, "FName": "International- Italy - Women", "TName": "Italy - Women" },
{ "TId": 336, "FName": "International- Mexico", "TName": "Mexico" },
{ "TId": 337, "FName": "International- Mexico - Women", "TName": "Mexico - Women" },
{ "TId": 338, "FName": "International- Netherlands", "TName": "Netherlands" },
{ "TId": 339, "FName": "International- Netherlands - Women", "TName": "Netherlands - Women" },
{ "TId": 340, "FName": "International- Northern Ireland", "TName": "Northern Ireland" },
{ "TId": 341, "FName": "International- Norway", "TName": "Norway" },
{ "TId": 342, "FName": "International- Norway - Women", "TName": "Norway - Women" },
{ "TId": 343, "FName": "International- Paraguay", "TName": "Paraguay" },
{ "TId": 344, "FName": "International- Peru", "TName": "Peru" },
{ "TId": 345, "FName": "International- Poland", "TName": "Poland" },
{ "TId": 346, "FName": "International- Portugal", "TName": "Portugal" },
{ "TId": 347, "FName": "International- Republic of Ireland", "TName": "Republic of Ireland" },
{ "TId": 348, "FName": "International- Romania", "TName": "Romania" },
{ "TId": 349, "FName": "International- Russia", "TName": "Russia" },
{ "TId": 350, "FName": "International- Scotland", "TName": "Scotland" },
{ "TId": 351, "FName": "International- Slovenia", "TName": "Slovenia" },
{ "TId": 352, "FName": "International- South Africa", "TName": "South Africa" },
{ "TId": 353, "FName": "International- Spain", "TName": "Spain" },
{ "TId": 354, "FName": "International- Spain - Women", "TName": "Spain - Women" },
{ "TId": 355, "FName": "International- Sweden", "TName": "Sweden" },
{ "TId": 356, "FName": "International- Sweden - Women", "TName": "Sweden - Women" },
{ "TId": 357, "FName": "International- Switzerland", "TName": "Switzerland" },
{ "TId": 358, "FName": "International- Turkey", "TName": "Turkey" },
{ "TId": 359, "FName": "International- United States", "TName": "United States" },
{ "TId": 360, "FName": "International- United States - Women", "TName": "United States - Women" },
{ "TId": 361, "FName": "International- Uruguay", "TName": "Uruguay" },
{ "TId": 362, "FName": "International- Venezuela", "TName": "Venezuela" },
{ "TId": 363, "FName": "International- Wales", "TName": "Wales" },
{ "TId": 364, "FName": "Ireland- Bohemian FC", "TName": "Bohemian FC" },
{ "TId": 365, "FName": "Ireland- Bray Wanderers", "TName": "Bray Wanderers" },
{ "TId": 366, "FName": "Ireland- Cork City", "TName": "Cork City" },
{ "TId": 367, "FName": "Ireland- Derry City", "TName": "Derry City" },
{ "TId": 368, "FName": "Ireland- Dundalk FC", "TName": "Dundalk FC" },
{ "TId": 369, "FName": "Ireland- Finn Harps", "TName": "Finn Harps" },
{ "TId": 370, "FName": "Ireland- Galway United", "TName": "Galway United" },
{ "TId": 371, "FName": "Ireland- Longford Town", "TName": "Longford Town" },
{ "TId": 372, "FName": "Ireland- Shamrock Rovers", "TName": "Shamrock Rovers" },
{ "TId": 373, "FName": "Ireland- Sligo Rovers", "TName": "Sligo Rovers" },
{ "TId": 374, "FName": "Ireland- St. Patrick's Athletic", "TName": "St. Patrick's Athletic" },
{ "TId": 375, "FName": "Ireland- Wexford Youths", "TName": "Wexford Youths" },
{ "TId": 376, "FName": "Italy- Ascoli", "TName": "Ascoli" },
{ "TId": 377, "FName": "Italy- Atalanta", "TName": "Atalanta" },
{ "TId": 378, "FName": "Italy- Avellino", "TName": "Avellino" },
{ "TId": 379, "FName": "Italy- Bari", "TName": "Bari" },
{ "TId": 380, "FName": "Italy- Benevento", "TName": "Benevento" },
{ "TId": 381, "FName": "Italy- Bologna", "TName": "Bologna" },
{ "TId": 382, "FName": "Italy- Brescia", "TName": "Brescia" },
{ "TId": 383, "FName": "Italy- Cagliari", "TName": "Cagliari" },
{ "TId": 384, "FName": "Italy- Carpi", "TName": "Carpi" },
{ "TId": 385, "FName": "Italy- Cesena", "TName": "Cesena" },
{ "TId": 386, "FName": "Italy- Chievo Verona", "TName": "Chievo Verona" },
{ "TId": 387, "FName": "Italy- Cittadella", "TName": "Cittadella" },
{ "TId": 388, "FName": "Italy- Crotone", "TName": "Crotone" },
{ "TId": 389, "FName": "Italy- Empoli", "TName": "Empoli" },
{ "TId": 390, "FName": "Italy- Fiorentina", "TName": "Fiorentina" },
{ "TId": 391, "FName": "Italy- Frosinone", "TName": "Frosinone" },
{ "TId": 392, "FName": "Italy- Genoa", "TName": "Genoa" },
{ "TId": 393, "FName": "Italy- Hellas Verona", "TName": "Hellas Verona" },
{ "TId": 394, "FName": "Italy- Inter", "TName": "Inter" },
{ "TId": 395, "FName": "Italy- Juventus", "TName": "Juventus" },
{ "TId": 396, "FName": "Italy- Latina", "TName": "Latina" },
{ "TId": 397, "FName": "Italy- Lazio", "TName": "Lazio" },
{ "TId": 398, "FName": "Italy- Milan", "TName": "Milan" },
{ "TId": 399, "FName": "Italy- Napoli", "TName": "Napoli" },
{ "TId": 400, "FName": "Italy- Novara", "TName": "Novara" },
{ "TId": 401, "FName": "Italy- Palermo", "TName": "Palermo" },
{ "TId": 402, "FName": "Italy- Perugia", "TName": "Perugia" },
{ "TId": 403, "FName": "Italy- Pescara", "TName": "Pescara" },
{ "TId": 404, "FName": "Italy- Pisa", "TName": "Pisa" },
{ "TId": 405, "FName": "Italy- Pro Vercelli", "TName": "Pro Vercelli" },
{ "TId": 406, "FName": "Italy- Roma", "TName": "Roma" },
{ "TId": 407, "FName": "Italy- Salernitana", "TName": "Salernitana" },
{ "TId": 408, "FName": "Italy- Sampdoria", "TName": "Sampdoria" },
{ "TId": 409, "FName": "Italy- Sassuolo", "TName": "Sassuolo" },
{ "TId": 410, "FName": "Italy- Spal", "TName": "Spal" },
{ "TId": 411, "FName": "Italy- Spezia", "TName": "Spezia" },
{ "TId": 412, "FName": "Italy- Ternana", "TName": "Ternana" },
{ "TId": 413, "FName": "Italy- Torino", "TName": "Torino" },
{ "TId": 414, "FName": "Italy- Trapani", "TName": "Trapani" },
{ "TId": 415, "FName": "Italy- Udinese", "TName": "Udinese" },
{ "TId": 416, "FName": "Italy- Vicenza", "TName": "Vicenza" },
{ "TId": 417, "FName": "Italy- Virtus Entella", "TName": "Virtus Entella" },
{ "TId": 418, "FName": "Japan- Albirex Niigata", "TName": "Albirex Niigata" },
{ "TId": 419, "FName": "Japan- Avispa Fukuoka", "TName": "Avispa Fukuoka" },
{ "TId": 420, "FName": "Japan- FC Tokyo", "TName": "FC Tokyo" },
{ "TId": 421, "FName": "Japan- Gamba Osaka", "TName": "Gamba Osaka" },
{ "TId": 422, "FName": "Japan- Jubilo Iwata", "TName": "Jubilo Iwata" },
{ "TId": 423, "FName": "Japan- Kashima Antlers", "TName": "Kashima Antlers" },
{ "TId": 424, "FName": "Japan- Kashiwa Reysol", "TName": "Kashiwa Reysol" },
{ "TId": 425, "FName": "Japan- Kawasaki Frontale", "TName": "Kawasaki Frontale" },
{ "TId": 426, "FName": "Japan- Nagoya Grampus", "TName": "Nagoya Grampus" },
{ "TId": 427, "FName": "Japan- Omiya Ardija", "TName": "Omiya Ardija" },
{ "TId": 428, "FName": "Japan- Sagan Tosu", "TName": "Sagan Tosu" },
{ "TId": 429, "FName": "Japan- Sanfrecce Hiroshima", "TName": "Sanfrecce Hiroshima" },
{ "TId": 430, "FName": "Japan- Shonan Bellmare", "TName": "Shonan Bellmare" },
{ "TId": 431, "FName": "Japan- Urawa Red Diamonds", "TName": "Urawa Red Diamonds" },
{ "TId": 432, "FName": "Japan- Vegalta Sendai", "TName": "Vegalta Sendai" },
{ "TId": 433, "FName": "Japan- Ventforet Kofu", "TName": "Ventforet Kofu" },
{ "TId": 434, "FName": "Japan- Vissel Kobe", "TName": "Vissel Kobe" },
{ "TId": 435, "FName": "Japan- Yokohama F. Marinos", "TName": "Yokohama F. Marinos" },
{ "TId": 436, "FName": "Mexico- America", "TName": "America" },
{ "TId": 437, "FName": "Mexico- Atlas", "TName": "Atlas" },
{ "TId": 438, "FName": "Mexico- Chiapas FC", "TName": "Chiapas FC" },
{ "TId": 439, "FName": "Mexico- Cruz Azul", "TName": "Cruz Azul" },
{ "TId": 440, "FName": "Mexico- Gallos Blancos de Queretaro", "TName": "Gallos Blancos de Queretaro" },
{ "TId": 441, "FName": "Mexico- Guadalajara", "TName": "Guadalajara" },
{ "TId": 442, "FName": "Mexico- Leon", "TName": "Leon" },
{ "TId": 443, "FName": "Mexico- Monarcas Morelia", "TName": "Monarcas Morelia" },
{ "TId": 444, "FName": "Mexico- Monterrey", "TName": "Monterrey" },
{ "TId": 445, "FName": "Mexico- Necaxa", "TName": "Necaxa" },
{ "TId": 446, "FName": "Mexico- Pachuca", "TName": "Pachuca" },
{ "TId": 447, "FName": "Mexico- Puebla", "TName": "Puebla" },
{ "TId": 448, "FName": "Mexico- Santos Laguna", "TName": "Santos Laguna" },
{ "TId": 449, "FName": "Mexico- Tiburones Rojos de Veracruz", "TName": "Tiburones Rojos de Veracruz" },
{ "TId": 450, "FName": "Mexico- Tigres U.A.N.L.", "TName": "Tigres U.A.N.L." },
{ "TId": 451, "FName": "Mexico- Tijuana", "TName": "Tijuana" },
{ "TId": 452, "FName": "Mexico- Toluca", "TName": "Toluca" },
{ "TId": 453, "FName": "Mexico- U.N.A.M.", "TName": "U.N.A.M." },
{ "TId": 454, "FName": "Netherlands- ADO Den Haag", "TName": "ADO Den Haag" },
{ "TId": 455, "FName": "Netherlands- Ajax", "TName": "Ajax" },
{ "TId": 456, "FName": "Netherlands- AZ", "TName": "AZ" },
{ "TId": 457, "FName": "Netherlands- Excelsior", "TName": "Excelsior" },
{ "TId": 458, "FName": "Netherlands- FC Groningen", "TName": "FC Groningen" },
{ "TId": 459, "FName": "Netherlands- FC Twente", "TName": "FC Twente" },
{ "TId": 460, "FName": "Netherlands- FC Utrecht", "TName": "FC Utrecht" },
{ "TId": 461, "FName": "Netherlands- Feyenoord", "TName": "Feyenoord" },
{ "TId": 462, "FName": "Netherlands- Go Ahead Eagles", "TName": "Go Ahead Eagles" },
{ "TId": 463, "FName": "Netherlands- Heracles Almelo", "TName": "Heracles Almelo" },
{ "TId": 464, "FName": "Netherlands- NEC", "TName": "NEC" },
{ "TId": 465, "FName": "Netherlands- PEC Zwolle", "TName": "PEC Zwolle" },
{ "TId": 466, "FName": "Netherlands- PSV", "TName": "PSV" },
{ "TId": 467, "FName": "Netherlands- Roda JC Kerkrade", "TName": "Roda JC Kerkrade" },
{ "TId": 468, "FName": "Netherlands- SC Heerenveen", "TName": "SC Heerenveen" },
{ "TId": 469, "FName": "Netherlands- Sparta Rotterdam", "TName": "Sparta Rotterdam" },
{ "TId": 470, "FName": "Netherlands- Vitesse", "TName": "Vitesse" },
{ "TId": 471, "FName": "Netherlands- Willem II", "TName": "Willem II" },
{ "TId": 472, "FName": "Norway- Aalesunds FK", "TName": "Aalesunds FK" },
{ "TId": 473, "FName": "Norway- FK Bodo/Glimt", "TName": "FK Bodo/Glimt" },
{ "TId": 474, "FName": "Norway- FK Haugesund", "TName": "FK Haugesund" },
{ "TId": 475, "FName": "Norway- IK Start", "TName": "IK Start" },
{ "TId": 476, "FName": "Norway- Lillestrom SK", "TName": "Lillestrom SK" },
{ "TId": 477, "FName": "Norway- Molde FK", "TName": "Molde FK" },
{ "TId": 478, "FName": "Norway- Odds Ballklubb", "TName": "Odds Ballklubb" },
{ "TId": 479, "FName": "Norway- Rosenborg BK", "TName": "Rosenborg BK" },
{ "TId": 480, "FName": "Norway- Sarpsborg 08 FF", "TName": "Sarpsborg 08 FF" },
{ "TId": 481, "FName": "Norway- SK Brann", "TName": "SK Brann" },
{ "TId": 482, "FName": "Norway- Sogndal Fotball", "TName": "Sogndal Fotball" },
{ "TId": 483, "FName": "Norway- Stabæk Fotball", "TName": "Stabæk Fotball" },
{ "TId": 484, "FName": "Norway- Stromsgodset Toppfotball", "TName": "Stromsgodset Toppfotball" },
{ "TId": 485, "FName": "Norway- Tromso IL", "TName": "Tromso IL" },
{ "TId": 486, "FName": "Norway- Valerenga", "TName": "Valerenga" },
{ "TId": 487, "FName": "Norway- Viking FK", "TName": "Viking FK" },
{ "TId": 488, "FName": "Poland- Arka Gdynia", "TName": "Arka Gdynia" },
{ "TId": 489, "FName": "Poland- Bruk-Bet Termalica Nieciecza", "TName": "Bruk-Bet Termalica Nieciecza" },
{ "TId": 490, "FName": "Poland- Cracovia Krakow", "TName": "Cracovia Krakow" },
{ "TId": 491, "FName": "Poland- Gornik Leczna", "TName": "Gornik Leczna" },
{ "TId": 492, "FName": "Poland- Jagiellonia BiaLystok", "TName": "Jagiellonia BiaLystok" },
{ "TId": 493, "FName": "Poland- Korona Kielce", "TName": "Korona Kielce" },
{ "TId": 494, "FName": "Poland- Lech Poznań", "TName": "Lech Poznań" },
{ "TId": 495, "FName": "Poland- Lechia Gdańsk", "TName": "Lechia Gdańsk" },
{ "TId": 496, "FName": "Poland- Legia Warszawa", "TName": "Legia Warszawa" },
{ "TId": 497, "FName": "Poland- Piast Gliwice", "TName": "Piast Gliwice" },
{ "TId": 498, "FName": "Poland- Pogoń Szczecin", "TName": "Pogoń Szczecin" },
{ "TId": 499, "FName": "Poland- Ruch Chorzow", "TName": "Ruch Chorzow" },
{ "TId": 500, "FName": "Poland- Slask WrocLaw", "TName": "Slask WrocLaw" },
{ "TId": 501, "FName": "Poland- WisLa Krakow", "TName": "WisLa Krakow" },
{ "TId": 502, "FName": "Poland- WisLa Plock", "TName": "WisLa Plock" },
{ "TId": 503, "FName": "Poland- ZagLebie Lubin", "TName": "ZagLebie Lubin" },
{ "TId": 504, "FName": "Portugal- Arouca", "TName": "Arouca" },
{ "TId": 505, "FName": "Portugal- Belenenses", "TName": "Belenenses" },
{ "TId": 506, "FName": "Portugal- Boavista", "TName": "Boavista" },
{ "TId": 507, "FName": "Portugal- Chaves", "TName": "Chaves" },
{ "TId": 508, "FName": "Portugal- Estoril Praia", "TName": "Estoril Praia" },
{ "TId": 509, "FName": "Portugal- FC Porto", "TName": "FC Porto" },
{ "TId": 510, "FName": "Portugal- Feirense", "TName": "Feirense" },
{ "TId": 511, "FName": "Portugal- Marítimo", "TName": "Marítimo" },
{ "TId": 512, "FName": "Portugal- Moreirense", "TName": "Moreirense" },
{ "TId": 513, "FName": "Portugal- Nacional", "TName": "Nacional" },
{ "TId": 514, "FName": "Portugal- Pacos de Ferreira", "TName": "Pacos de Ferreira" },
{ "TId": 515, "FName": "Portugal- Rio Ave", "TName": "Rio Ave" },
{ "TId": 516, "FName": "Portugal- SC Braga", "TName": "SC Braga" },
{ "TId": 517, "FName": "Portugal- SL Benfica", "TName": "SL Benfica" },
{ "TId": 518, "FName": "Portugal- Sporting CP", "TName": "Sporting CP" },
{ "TId": 519, "FName": "Portugal- Tondela", "TName": "Tondela" },
{ "TId": 520, "FName": "Portugal- Vitoria Guimaraes", "TName": "Vitoria Guimaraes" },
{ "TId": 521, "FName": "Portugal- Vitoria Setubal", "TName": "Vitoria Setubal" },
{ "TId": 522, "FName": "REST OF WORLD- adidas All-Star Team", "TName": "adidas All-Star Team" },
{ "TId": 523, "FName": "REST OF WORLD- Avaí", "TName": "Avaí" },
{ "TId": 524, "FName": "REST OF WORLD- Classic XI", "TName": "Classic XI" },
{ "TId": 525, "FName": "REST OF WORLD- Criciuma", "TName": "Criciuma" },
{ "TId": 526, "FName": "REST OF WORLD- Goias", "TName": "Goias" },
{ "TId": 527, "FName": "REST OF WORLD- HJK Helsinki", "TName": "HJK Helsinki" },
{ "TId": 528, "FName": "REST OF WORLD- Joinville", "TName": "Joinville" },
{ "TId": 529, "FName": "REST OF WORLD- Kaizer Chiefs", "TName": "Kaizer Chiefs" },
{ "TId": 530, "FName": "REST OF WORLD- MLS All Stars", "TName": "MLS All Stars" },
{ "TId": 531, "FName": "REST OF WORLD- Olympiacos CFP", "TName": "Olympiacos CFP" },
{ "TId": 532, "FName": "REST OF WORLD- Orlando Pirates", "TName": "Orlando Pirates" },
{ "TId": 533, "FName": "REST OF WORLD- Panathinaikos FC", "TName": "Panathinaikos FC" },
{ "TId": 534, "FName": "REST OF WORLD- PAOK FC", "TName": "PAOK FC" },
{ "TId": 535, "FName": "REST OF WORLD- Shakhtar Donetsk", "TName": "Shakhtar Donetsk" },
{ "TId": 536, "FName": "REST OF WORLD- Vasco da Gama", "TName": "Vasco da Gama" },
{ "TId": 537, "FName": "REST OF WORLD- World XI", "TName": "World XI" },
{ "TId": 538, "FName": "Russia- Amkar Perm", "TName": "Amkar Perm" },
{ "TId": 539, "FName": "Russia- Anzhi Makhachkala", "TName": "Anzhi Makhachkala" },
{ "TId": 540, "FName": "Russia- Arsenal Tula", "TName": "Arsenal Tula" },
{ "TId": 541, "FName": "Russia- CSKA Moskva", "TName": "CSKA Moskva" },
{ "TId": 542, "FName": "Russia- FC Krasnodar", "TName": "FC Krasnodar" },
{ "TId": 543, "FName": "Russia- FC Orenburg", "TName": "FC Orenburg" },
{ "TId": 544, "FName": "Russia- FC Rostov", "TName": "FC Rostov" },
{ "TId": 545, "FName": "Russia- FC Ufa", "TName": "FC Ufa" },
{ "TId": 546, "FName": "Russia- FC Ural", "TName": "FC Ural" },
{ "TId": 547, "FName": "Russia- Krylya Sovetov Samara", "TName": "Krylya Sovetov Samara" },
{ "TId": 548, "FName": "Russia- Lokomotiv Moskva", "TName": "Lokomotiv Moskva" },
{ "TId": 549, "FName": "Russia- Rubin Kazan", "TName": "Rubin Kazan" },
{ "TId": 550, "FName": "Russia- Spartak Moskva", "TName": "Spartak Moskva" },
{ "TId": 551, "FName": "Russia- Terek Grozny", "TName": "Terek Grozny" },
{ "TId": 552, "FName": "Russia- Tom Tomsk", "TName": "Tom Tomsk" },
{ "TId": 553, "FName": "Russia- Zenit St. Petersburg", "TName": "Zenit St. Petersburg" },
{ "TId": 554, "FName": "Saudi Arabia- Al Ahli", "TName": "Al Ahli" },
{ "TId": 555, "FName": "Saudi Arabia- Al Batin", "TName": "Al Batin" },
{ "TId": 556, "FName": "Saudi Arabia- Al Ettifaq", "TName": "Al Ettifaq" },
{ "TId": 557, "FName": "Saudi Arabia- Al Faisaly", "TName": "Al Faisaly" },
{ "TId": 558, "FName": "Saudi Arabia- Al Fateh", "TName": "Al Fateh" },
{ "TId": 559, "FName": "Saudi Arabia- Al Hilal", "TName": "Al Hilal" },
{ "TId": 560, "FName": "Saudi Arabia- Al Ittihad", "TName": "Al Ittihad" },
{ "TId": 561, "FName": "Saudi Arabia- Al Khaleej", "TName": "Al Khaleej" },
{ "TId": 562, "FName": "Saudi Arabia- Al Nassr", "TName": "Al Nassr" },
{ "TId": 563, "FName": "Saudi Arabia- Al Qadisiyah", "TName": "Al Qadisiyah" },
{ "TId": 564, "FName": "Saudi Arabia- Al Raed", "TName": "Al Raed" },
{ "TId": 565, "FName": "Saudi Arabia- Al Shabab", "TName": "Al Shabab" },
{ "TId": 566, "FName": "Saudi Arabia- Al Taawoun", "TName": "Al Taawoun" },
{ "TId": 567, "FName": "Saudi Arabia- Al Wehda", "TName": "Al Wehda" },
{ "TId": 568, "FName": "Scotland- Aberdeen", "TName": "Aberdeen" },
{ "TId": 569, "FName": "Scotland- Celtic", "TName": "Celtic" },
{ "TId": 570, "FName": "Scotland- Dundee FC", "TName": "Dundee FC" },
{ "TId": 571, "FName": "Scotland- Hamilton Academical", "TName": "Hamilton Academical" },
{ "TId": 572, "FName": "Scotland- Heart of Midlothian", "TName": "Heart of Midlothian" },
{ "TId": 573, "FName": "Scotland- Inverness Caledonian Thistle", "TName": "Inverness Caledonian Thistle" },
{ "TId": 574, "FName": "Scotland- Kilmarnock", "TName": "Kilmarnock" },
{ "TId": 575, "FName": "Scotland- Motherwell", "TName": "Motherwell" },
{ "TId": 576, "FName": "Scotland- Partick Thistle", "TName": "Partick Thistle" },
{ "TId": 577, "FName": "Scotland- Rangers", "TName": "Rangers" },
{ "TId": 578, "FName": "Scotland- Ross County", "TName": "Ross County" },
{ "TId": 579, "FName": "Scotland- St. Johnstone", "TName": "St. Johnstone" },
{ "TId": 580, "FName": "South Korea- FC Seoul", "TName": "FC Seoul" },
{ "TId": 581, "FName": "South Korea- Gwangju FC", "TName": "Gwangju FC" },
{ "TId": 582, "FName": "South Korea- Incheon United", "TName": "Incheon United" },
{ "TId": 583, "FName": "South Korea- Jeju United", "TName": "Jeju United" },
{ "TId": 584, "FName": "South Korea- Jeonbuk Hyundai Motors", "TName": "Jeonbuk Hyundai Motors" },
{ "TId": 585, "FName": "South Korea- Jeonnam Dragons", "TName": "Jeonnam Dragons" },
{ "TId": 586, "FName": "South Korea- Pohang Steelers", "TName": "Pohang Steelers" },
{ "TId": 587, "FName": "South Korea- Sangju Sangmu", "TName": "Sangju Sangmu" },
{ "TId": 588, "FName": "South Korea- Seongnam FC", "TName": "Seongnam FC" },
{ "TId": 589, "FName": "South Korea- Suwon FC", "TName": "Suwon FC" },
{ "TId": 590, "FName": "South Korea- Suwon Samsung Bluewings", "TName": "Suwon Samsung Bluewings" },
{ "TId": 591, "FName": "South Korea- Ulsan Hyundai", "TName": "Ulsan Hyundai" },
{ "TId": 592, "FName": "Spain- AD Alcorcon", "TName": "AD Alcorcon" },
{ "TId": 593, "FName": "Spain- Athletic Club de Bilbao", "TName": "Athletic Club de Bilbao" },
{ "TId": 594, "FName": "Spain- Atletico de Madrid", "TName": "Atletico de Madrid" },
{ "TId": 595, "FName": "Spain- CA Osasuna", "TName": "CA Osasuna" },
{ "TId": 596, "FName": "Spain- Cadiz CF", "TName": "Cadiz CF" },
{ "TId": 597, "FName": "Spain- CD Leganes", "TName": "CD Leganes" },
{ "TId": 598, "FName": "Spain- CD Lugo", "TName": "CD Lugo" },
{ "TId": 599, "FName": "Spain- CD Mirandes", "TName": "CD Mirandes" },
{ "TId": 600, "FName": "Spain- CD Numancia", "TName": "CD Numancia" },
{ "TId": 601, "FName": "Spain- CD Tenerife", "TName": "CD Tenerife" },
{ "TId": 602, "FName": "Spain- CF Reus Deportiu", "TName": "CF Reus Deportiu" },
{ "TId": 603, "FName": "Spain- Cordoba CF", "TName": "Cordoba CF" },
{ "TId": 604, "FName": "Spain- Deportivo Alaves", "TName": "Deportivo Alaves" },
{ "TId": 605, "FName": "Spain- Elche CF", "TName": "Elche CF" },
{ "TId": 606, "FName": "Spain- FC Barcelona", "TName": "FC Barcelona" },
{ "TId": 607, "FName": "Spain- Getafe CF", "TName": "Getafe CF" },
{ "TId": 608, "FName": "Spain- Girona FC", "TName": "Girona FC" },
{ "TId": 609, "FName": "Spain- Granada CF", "TName": "Granada CF" },
{ "TId": 610, "FName": "Spain- Levante UD", "TName": "Levante UD" },
{ "TId": 611, "FName": "Spain- Malaga CF", "TName": "Malaga CF" },
{ "TId": 612, "FName": "Spain- Nastic de Tarragona", "TName": "Nastic de Tarragona" },
{ "TId": 613, "FName": "Spain- Rayo Vallecano", "TName": "Rayo Vallecano" },
{ "TId": 614, "FName": "Spain- RC Celta de Vigo", "TName": "RC Celta de Vigo" },
{ "TId": 615, "FName": "Spain- RC Deportivo", "TName": "RC Deportivo" },
{ "TId": 616, "FName": "Spain- RCD Espanyol", "TName": "RCD Espanyol" },
{ "TId": 617, "FName": "Spain- RCD Mallorca", "TName": "RCD Mallorca" },
{ "TId": 618, "FName": "Spain- Real Betis Balompie", "TName": "Real Betis Balompie" },
{ "TId": 619, "FName": "Spain- Real Madrid", "TName": "Real Madrid" },
{ "TId": 620, "FName": "Spain- Real Oviedo", "TName": "Real Oviedo" },
{ "TId": 621, "FName": "Spain- Real Sociedad", "TName": "Real Sociedad" },
{ "TId": 622, "FName": "Spain- Real Sporting de Gijon", "TName": "Real Sporting de Gijon" },
{ "TId": 623, "FName": "Spain- Real Valladolid", "TName": "Real Valladolid" },
{ "TId": 624, "FName": "Spain- Real Zaragoza", "TName": "Real Zaragoza" },
{ "TId": 625, "FName": "Spain- SD Eibar", "TName": "SD Eibar" },
{ "TId": 626, "FName": "Spain- SD Huesca", "TName": "SD Huesca" },
{ "TId": 627, "FName": "Spain- Sevilla Atletico", "TName": "Sevilla Atletico" },
{ "TId": 628, "FName": "Spain- Sevilla FC", "TName": "Sevilla FC" },
{ "TId": 629, "FName": "Spain- UCAM Murcia", "TName": "UCAM Murcia" },
{ "TId": 630, "FName": "Spain- UD Almería", "TName": "UD Almería" },
{ "TId": 631, "FName": "Spain- UD Las Palmas", "TName": "UD Las Palmas" },
{ "TId": 632, "FName": "Spain- Valencia CF", "TName": "Valencia CF" },
{ "TId": 633, "FName": "Spain- Villarreal CF", "TName": "Villarreal CF" },
{ "TId": 634, "FName": "Sweden- AIK", "TName": "AIK" },
{ "TId": 635, "FName": "Sweden- BK Hacken", "TName": "BK Hacken" },
{ "TId": 636, "FName": "Sweden- Djurgardens IF", "TName": "Djurgardens IF" },
{ "TId": 637, "FName": "Sweden- Falkenbergs FF", "TName": "Falkenbergs FF" },
{ "TId": 638, "FName": "Sweden- Gefle IF", "TName": "Gefle IF" },
{ "TId": 639, "FName": "Sweden- GIF Sundsvall", "TName": "GIF Sundsvall" },
{ "TId": 640, "FName": "Sweden- Hammarby IF", "TName": "Hammarby IF" },
{ "TId": 641, "FName": "Sweden- Helsingborgs IF", "TName": "Helsingborgs IF" },
{ "TId": 642, "FName": "Sweden- IF Elfsborg", "TName": "IF Elfsborg" },
{ "TId": 643, "FName": "Sweden- IFK Goteborg", "TName": "IFK Goteborg" },
{ "TId": 644, "FName": "Sweden- IFK Norrkoping", "TName": "IFK Norrkoping" },
{ "TId": 645, "FName": "Sweden- Jonkopings Sodra IF", "TName": "Jonkopings Sodra IF" },
{ "TId": 646, "FName": "Sweden- Kalmar FF", "TName": "Kalmar FF" },
{ "TId": 647, "FName": "Sweden- Malmo FF", "TName": "Malmo FF" },
{ "TId": 648, "FName": "Sweden- orebro SK", "TName": "orebro SK" },
{ "TId": 649, "FName": "Sweden- ostersunds FK", "TName": "ostersunds FK" },
{ "TId": 650, "FName": "Switzerland- BSC Young Boys", "TName": "BSC Young Boys" },
{ "TId": 651, "FName": "Switzerland- FC Basel", "TName": "FC Basel" },
{ "TId": 652, "FName": "Switzerland- FC Lausanne-Sport", "TName": "FC Lausanne-Sport" },
{ "TId": 653, "FName": "Switzerland- FC Lugano", "TName": "FC Lugano" },
{ "TId": 654, "FName": "Switzerland- FC Luzern", "TName": "FC Luzern" },
{ "TId": 655, "FName": "Switzerland- FC Sion", "TName": "FC Sion" },
{ "TId": 656, "FName": "Switzerland- FC St. Gallen", "TName": "FC St. Gallen" },
{ "TId": 657, "FName": "Switzerland- FC Thun", "TName": "FC Thun" },
{ "TId": 658, "FName": "Switzerland- FC Vaduz", "TName": "FC Vaduz" },
{ "TId": 659, "FName": "Switzerland- Grasshopper Club Znurich", "TName": "Grasshopper Club Znurich" },
{ "TId": 660, "FName": "Turkey- Adanaspor", "TName": "Adanaspor" },
{ "TId": 661, "FName": "Turkey- Akhisarspor", "TName": "Akhisarspor" },
{ "TId": 662, "FName": "Turkey- Alanyaspor", "TName": "Alanyaspor" },
{ "TId": 663, "FName": "Turkey- Antalyaspor", "TName": "Antalyaspor" },
{ "TId": 664, "FName": "Turkey- Atiker Konyaspor", "TName": "Atiker Konyaspor" },
{ "TId": 665, "FName": "Turkey- Besiktas", "TName": "Besiktas" },
{ "TId": 666, "FName": "Turkey- Bursaspor", "TName": "Bursaspor" },
{ "TId": 667, "FName": "Turkey- Caykur Rizespor", "TName": "Caykur Rizespor" },
{ "TId": 668, "FName": "Turkey- Fenerbahce", "TName": "Fenerbahce" },
{ "TId": 669, "FName": "Turkey- Galatasaray", "TName": "Galatasaray" },
{ "TId": 670, "FName": "Turkey- Gaziantepspor", "TName": "Gaziantepspor" },
{ "TId": 671, "FName": "Turkey- Genclerbirligi", "TName": "Genclerbirligi" },
{ "TId": 672, "FName": "Turkey- Kardemir Karabnukspor", "TName": "Kardemir Karabnukspor" },
{ "TId": 673, "FName": "Turkey- Kasımpasa", "TName": "Kasımpasa" },
{ "TId": 674, "FName": "Turkey- Kayserispor", "TName": "Kayserispor" },
{ "TId": 675, "FName": "Turkey- Medipol Basaksehir", "TName": "Medipol Basaksehir" },
{ "TId": 676, "FName": "Turkey- Osmanlıspor", "TName": "Osmanlıspor" },
{ "TId": 677, "FName": "Turkey- Trabzonspor", "TName": "Trabzonspor" },
{ "TId": 678, "FName": "USA- Chicago Fire", "TName": "Chicago Fire" },
{ "TId": 679, "FName": "USA- Colorado Rapids", "TName": "Colorado Rapids" },
{ "TId": 680, "FName": "USA- Columbus Crew SC", "TName": "Columbus Crew SC" },
{ "TId": 681, "FName": "USA- DC United", "TName": "DC United" },
{ "TId": 682, "FName": "USA- FC Dallas", "TName": "FC Dallas" },
{ "TId": 683, "FName": "USA- Houston Dynamo", "TName": "Houston Dynamo" },
{ "TId": 684, "FName": "USA- Los Angeles Galaxy", "TName": "Los Angeles Galaxy" },
{ "TId": 685, "FName": "USA- Montreal Impact", "TName": "Montreal Impact" },
{ "TId": 686, "FName": "USA- New England Revolution", "TName": "New England Revolution" },
{ "TId": 687, "FName": "USA- New York City FC", "TName": "New York City FC" },
{ "TId": 688, "FName": "USA- New York Red Bulls", "TName": "New York Red Bulls" },
{ "TId": 689, "FName": "USA- Orlando City SC", "TName": "Orlando City SC" },
{ "TId": 690, "FName": "USA- Philadelphia Union", "TName": "Philadelphia Union" },
{ "TId": 691, "FName": "USA- Portland Timbers", "TName": "Portland Timbers" },
{ "TId": 692, "FName": "USA- Real Salt Lake", "TName": "Real Salt Lake" },
{ "TId": 693, "FName": "USA- San Jose Earthquakes", "TName": "San Jose Earthquakes" },
{ "TId": 694, "FName": "USA- Seattle Sounders", "TName": "Seattle Sounders" },
{ "TId": 695, "FName": "USA- Sporting KC", "TName": "Sporting KC" },
{ "TId": 696, "FName": "USA- Toronto FC", "TName": "Toronto FC" },
{ "TId": 697, "FName": "USA- Vancouver Whitecaps", "TName": "Vancouver Whitecaps" }
];
