//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FifaSMmvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FmScore
    {
        public bool IsUpdate { get; set; }
        public int Id { get; set; }
        public DateTime? MatchDt { get; set; }
        public int Player1 { get; set; }
        public int Team1 { get; set; }
        public int Goals1 { get; set; }
        public int Player2 { get; set; }
        public int Team2 { get; set; }
        public int Goals2 { get; set; }
    
        //public virtual Player Player { get; set; }
        //public virtual Player Player3 { get; set; }
    }
}
